name: Update README with Bitcoin Price

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fetch Bitcoin Price
        run: |
          BTC_PRICE=$(curl -s https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd | jq -r '.bitcoin.usd')
          echo "BTC_PRICE=$BTC_PRICE" >> $GITHUB_ENV
      
      - name: Update README
        run: |
          sed -i "s/Bitcoin Price: \$.*/Bitcoin Price: \$$BTC_PRICE USD/g" README.md
        env:
          BTC_PRICE: ${{ env.BTC_PRICE }}
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update Bitcoin price" -a || echo "No changes to commit"
          git push || echo "No changes to push"

